# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mike D
tagline:          'Programmer'
description:      'I am awesome.'
url:              http://mike1d.github.io
baseurl:          /

author:
  name:           'Mike D'
  url:            http://mike1d.github.io
